name: "Python CI"
on:
  workflow_dispatch:      
    inputs:
      job_name:
        description: 'Name of the job to modify'
        type: string
        required: true
        default: 'SQL Copy Job'
      weekdays_only:
        description: 'Should the job run only on weekdays?'
        type: boolean
        required: true
        default: false

permissions:
  contents: read

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install databricks-sdk

      - name: Run Python script
        env:
          JOB_NAME: ${{ github.event.inputs.job_name }}
          WEEKDAYS_ONLY: ${{ github.event.inputs.weekdays_only }}
        run: python scripts/modify_job.py